services:
  redis:
    container_name: ${APP_NAME}-redis
    image: redis:7.0.11-alpine
    ports:
      - ${REDIS_PORT}:6379
    restart: always
  postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres:15.3-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
